# pandas

pandas is a powerfull python library for manipulation and analyse the data

it is open source library

fast(built on top of numpy),flexibility

In [1]:
 pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.3

#### series-1d array(data structure) with label

In [4]:
l1=[1,2,3,4,5,6]
type(l1)

list

In [5]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
s=pd.Series(l1,index=["a","b","c","d","e","f"],name="my series")

In [7]:
s

a    1
b    2
c    3
d    4
e    5
f    6
Name: my series, dtype: int64

In [8]:
s['a']

np.int64(1)

In [9]:
type(s)

pandas.core.series.Series

In [10]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [11]:
s.values

array([1, 2, 3, 4, 5, 6])

note: index in series are immutable

In [12]:
s.index[0]='z'

TypeError: Index does not support mutable operations

In [ ]:
 ##changing the index of pandas a series
s.rename(index={'b':'y'})

a    1
y    2
c    3
d    4
e    5
f    6
Name: my series, dtype: int64

In [ ]:
s.rename(index={'b':'y'},inplace=True)

In [ ]:
s

a    1
y    2
c    3
d    4
e    5
f    6
Name: my series, dtype: int64

In [ ]:
import numpy as np

In [ ]:
dict1={'name':['virat','rohit','jadeja','bumrah'],
       'age':[34,35,35,34],
       'score':[180,67,56,np.nan],
       'role':['batsman','batsman','wicket keeper','all rounder']}
pd.DataFrame(dict1)

     name  age  score           role
0   virat   34  180.0        batsman
1   rohit   35   67.0        batsman
2  jadeja   35   56.0  wicket keeper
3  bumrah   34    NaN    all rounder

In [ ]:
df.count()

name     4
age      4
marks    4
role     4
dtype: int64

dataframe- its a 2d array (just like tables)

In [ ]:
dict1={'name':['virat','rohit','jadeja','bumrah'],
       'age':[34,35,35,34],
       'score':[180,67,56,87],
       'role':['batsman','batsman','wicket keeper','all rounder']}
pd.DataFrame(dict1)

     name  age  score           role
0   virat   34    180        batsman
1   rohit   35     67        batsman
2  jadeja   35     56  wicket keeper
3  bumrah   34     87    all rounder

In [ ]:
df=pd.DataFrame(dict1)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head(1)

    name  age  marks     role
0  virat   34    180  batsman

In [ ]:
df.tail()

     name  age  marks           role
0   virat   34    180        batsman
1   rohit   35     67        batsman
2  jadeja   35     56  wicket keeper
3  bumrah   34     87    all rounder

In [ ]:
df.tail(3)

     name  age  marks           role
1   rohit   35     67        batsman
2  jadeja   35     56  wicket keeper
3  bumrah   34     87    all rounder

In [ ]:
len(df)

4

In [ ]:
df.count()

name     4
age      4
marks    4
role     4
dtype: int64

In [ ]:
df.columns

Index(['name', 'age', 'marks', 'role'], dtype='object')

In [ ]:
df['name']

0     virat
1     rohit
2    jadeja
3    bumrah
Name: name, dtype: object

In [ ]:
type(df['name'])

pandas.core.series.Series

In [ ]:
df['name'].value_counts()

name
virat     1
rohit     1
jadeja    1
bumrah    1
Name: count, dtype: int64

In [ ]:
dict1={'name':['virat','rohit','jadeja','virat'],
       'age':[34,35,35,34],
       'score':[180,67,56,87],
       'role':['batsman','batsman','wicket keeper','all rounder']}
pd.DataFrame(dict1)

     name  age  score           role
0   virat   34    180        batsman
1   rohit   35     67        batsman
2  jadeja   35     56  wicket keeper
3   virat   34     87    all rounder

In [ ]:
df['name'].value_counts()

name
virat     1
rohit     1
jadeja    1
bumrah    1
Name: count, dtype: int64

### basic operations

> importing dataset from different files

> importing tabulardataset

In [ ]:
pd.read_csv()